name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build project
      run: make

    - name: Build & run project
      run: |
          make
          ./GameGirl "rom/Pokemon - Emerald Version.gba"

    - name: Build & run tests
      run: |
          make
          ./GameGirl "run_tests"

    - name: Build debug project
      run: make debug

    - name: Clean *.o
      run: make clean

    - name: Clean all
      run: make fclean

    - name: Re build project
      run: make re
